import { Property, Lead, Owner } from './types'

export const mockOwner: Owner = {
  id: '1',
  name: 'Marco Rossi',
  nickname: 'Marco',
  phone: '+39 333 456 7890',
  email: 'marco.rossi@email.com',
  language: 'italiano',
  contactHours: 'Lun-Ven 9:00–19:00',
  multipleProperties: true,
  supportContact: '+39 333 456 7890',
}

export const mockProperties: Property[] = [
  {
    id: '1',
    name: 'Bilocale Navigli',
    listingType: 'appartamento',
    rentalType: 'lungo',
    address: 'Via Vigevano 12, Milano',
    zone: 'Navigli',
    floor: 3,
    elevator: true,
    sqm: 65,
    rooms: 2,
    bathrooms: 1,
    maxGuests: 2,
    price: 1200,
    deposit: 2400,
    priceNegotiable: 'fisso',
    expensesIncluded: ['Wi-Fi', 'Riscaldamento'],
    furnished: 'completamente',
    smokingAllowed: 'no',
    petsAllowed: 'no',
    availableFrom: '2024-03-01',
    visitsAllowed: true,
    photos: 8,
    botActive: true,
    botTone: 'amichevole',
    canSharePhotos: true,
    escalationContact: '+39 333 456 7890',
    createdAt: '2024-01-15',
    completionPercent: 85,
  },
  {
    id: '2',
    name: 'Stanza Città Studi',
    listingType: 'stanza',
    rentalType: 'lungo',
    address: 'Via Ponzio 14, Milano',
    zone: 'Città Studi',
    floor: 2,
    elevator: false,
    sqm: 14,
    rooms: 1,
    bathrooms: 1,
    maxGuests: 1,
    price: 550,
    deposit: 1100,
    priceNegotiable: 'parzialmente',
    expensesIncluded: ['Wi-Fi', 'Luce', 'Gas', 'Acqua'],
    furnished: 'completamente',
    smokingAllowed: 'no',
    petsAllowed: 'no',
    availableFrom: '2024-02-15',
    visitsAllowed: true,
    photos: 5,
    botActive: true,
    botTone: 'neutro',
    canSharePhotos: true,
    escalationContact: '+39 333 456 7890',
    createdAt: '2024-01-20',
    completionPercent: 65,
  },
  {
    id: '3',
    name: 'Monolocale Isola',
    listingType: 'appartamento',
    rentalType: 'entrambi',
    address: 'Via Borsieri 8, Milano',
    zone: 'Isola',
    floor: 1,
    elevator: false,
    sqm: 38,
    rooms: 1,
    bathrooms: 1,
    maxGuests: 2,
    price: 900,
    deposit: 1800,
    priceNegotiable: 'fisso',
    expensesIncluded: ['Wi-Fi'],
    furnished: 'completamente',
    smokingAllowed: 'balcone',
    petsAllowed: 'dipende',
    availableFrom: '2024-03-15',
    visitsAllowed: true,
    photos: 3,
    botActive: false,
    botTone: 'neutro',
    canSharePhotos: false,
    escalationContact: '',
    createdAt: '2024-02-01',
    completionPercent: 40,
  },
]

export const mockLeads: Lead[] = [
  {
    id: '1',
    propertyId: '1',
    propertyName: 'Bilocale Navigli',
    name: 'Giulia Ferrari',
    whatsapp: '+39 349 123 4567',
    startDate: '2024-03-01',
    duration: '12 mesi',
    budget: '1.200€/mese',
    guests: 1,
    profile: 'lavoratore',
    documentsReady: 'si',
    residenceNeeded: 'no',
    visitRequested: true,
    visitDays: 'Sabato mattina',
    status: 'qualificato',
    actionSuggested: 'contatta',
    firstContact: '10 Feb, 09:23',
    lastUpdate: '10 Feb, 09:45',
    summary: 'Lavoratrice stabile, contratto indeterminato. Cerca bilocale da marzo, budget allineato. Documenti pronti, vuole visita sabato.',
  },
  {
    id: '2',
    propertyId: '1',
    propertyName: 'Bilocale Navigli',
    name: 'Ahmed Benali',
    whatsapp: '+39 342 987 6543',
    startDate: '2024-04-01',
    duration: '6 mesi',
    guests: 2,
    profile: 'studente',
    documentsReady: 'no',
    residenceNeeded: 'si',
    visitRequested: false,
    status: 'non_adatto',
    actionSuggested: 'rifiuta',
    firstContact: '9 Feb, 14:10',
    lastUpdate: '9 Feb, 14:35',
    summary: 'Studente universitario. Durata troppo breve, vuole residenza, documenti non pronti. Non allineato con i criteri.',
  },
  {
    id: '3',
    propertyId: '2',
    propertyName: 'Stanza Città Studi',
    name: 'Sofia Colombo',
    whatsapp: '+39 333 765 4321',
    startDate: '2024-02-20',
    duration: '10 mesi',
    budget: '550€/mese',
    guests: 1,
    profile: 'studente',
    documentsReady: 'si',
    residenceNeeded: 'no',
    visitRequested: true,
    visitDays: 'Mercoledì pomeriggio',
    status: 'qualificato',
    actionSuggested: 'contatta',
    firstContact: '8 Feb, 11:05',
    lastUpdate: '8 Feb, 11:30',
    summary: 'Studentessa Politecnico, iscrizione disponibile. Cerca stanza singola, disponibile a breve. Profilo ideale.',
  },
  {
    id: '4',
    propertyId: '1',
    propertyName: 'Bilocale Navigli',
    name: 'Luca Mancini',
    whatsapp: '+39 348 234 5678',
    startDate: '2024-03-15',
    duration: '12 mesi',
    budget: '1.100€/mese',
    guests: 2,
    profile: 'lavoratore',
    documentsReady: 'non_specificato',
    residenceNeeded: 'non_specificato',
    visitRequested: true,
    visitDays: 'Weekend',
    status: 'da_valutare',
    actionSuggested: 'richiedi_info',
    firstContact: '11 Feb, 16:40',
    lastUpdate: '11 Feb, 17:00',
    summary: 'Lavoratore, coppia. Budget sotto il prezzo richiesto. Vuole visita nel weekend. Richiede più informazioni.',
  },
  {
    id: '5',
    propertyId: '3',
    propertyName: 'Monolocale Isola',
    name: 'Emma Ricci',
    whatsapp: '+39 347 111 2233',
    startDate: '2024-03-20',
    duration: '6 mesi',
    budget: '900€/mese',
    guests: 1,
    profile: 'lavoratore',
    documentsReady: 'si',
    residenceNeeded: 'no',
    visitRequested: true,
    visitDays: 'Qualsiasi giorno feriale',
    status: 'qualificato',
    actionSuggested: 'contatta',
    firstContact: '11 Feb, 10:15',
    lastUpdate: '11 Feb, 10:40',
    summary: 'Professionista, trasferimento lavoro a Milano. Budget perfetto. Flessibile sulle date, documenti pronti.',
  },
]
